[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustysynth = { path = "../rustysynth" }
hound = "3.5.1"
indicatif = { version = "0.17.8", features = ["rayon"] }
